
["Delay Between Spawns"]
	#Default: 6000.0
	spawn_delay = 6000.0

["Daytime Spawning"]
	#Default: false
	spawn_daytime = false

["Attack Delay After Spawn"]
	#Default: 1500.0 [must be lower than max_attack_delay]
	min_attack_delay = 1500.0
	#Default: 2000.0 [must be higher than min_attack_delay]
	max_attack_delay = 2000.0

["Set Attack Damage"]
	#Default: 200.0
	attack_damage = 200.0

["Blood Rain Chance"]
	#Default: 5000.0 [minimum value: 1.0 - the higher the number, the rarer it is]
	blood_rain_chance = 5000.0

["Despawn Timer"]
	#Default: 800.0
	despawn_time = 800.0

["Spawn Chance"]
	#Default: 4000.0 [minimum value: 1.0 - the higher the number, the rarer it is]
	spawn_chance = 4000.0

["Step Height"]
	#Default: 10.0 [number of additional blocks The Boiled One can climb]
	step_height = 10.0

["Watching Chance When Player Sleeps"]
	#Default 0.2 [Min 0.0, Max 1.0, example 0.7 would be 70% chance when you sleep]
	watch_chance = 0.2

["Set Paralysis Effect Ticks after Watching"]
	#Default: 300.0
	paralysis_tick = 300.0

